package iso639_2

// Languages lookup table. Keys are ISO 639-1 and ISO 639-2 codes
var Languages = map[string]Language{
	"aa": {Alpha3: "aar", Alpha2: "aa", English: []string{"Afar"},
		French: []string{"afar"}},
	"aar": {Alpha3: "aar", Alpha2: "aa", English: []string{"Afar"},
		French: []string{"afar"}},
	"ab": {Alpha3: "abk", Alpha2: "ab", English: []string{"Abkhazian"},
		French: []string{"abkhaze"}},
	"abk": {Alpha3: "abk", Alpha2: "ab", English: []string{"Abkhazian"},
		French: []string{"abkhaze"}},
	"ace": {Alpha3: "ace", Alpha2: "", English: []string{"Achinese"},
		French: []string{"aceh"}},
	"ach": {Alpha3: "ach", Alpha2: "", English: []string{"Acoli"},
		French: []string{"acoli"}},
	"ada": {Alpha3: "ada", Alpha2: "", English: []string{"Adangme"},
		French: []string{"adangme"}},
	"ady": {Alpha3: "ady", Alpha2: "", English: []string{"Adyghe", "Adygei"},
		French: []string{"adyghé"}},
	"ae": {Alpha3: "ave", Alpha2: "ae", English: []string{"Avestan"},
		French: []string{"avestique"}},
	"af": {Alpha3: "afr", Alpha2: "af", English: []string{"Afrikaans"},
		French: []string{"afrikaans"}},
	"afa": {Alpha3: "afa", Alpha2: "", English: []string{"Afro-Asiatic languages"},
		French: []string{"afro-asiatiques, langues"}},
	"afh": {Alpha3: "afh", Alpha2: "", English: []string{"Afrihili"},
		French: []string{"afrihili"}},
	"afr": {Alpha3: "afr", Alpha2: "af", English: []string{"Afrikaans"},
		French: []string{"afrikaans"}},
	"ain": {Alpha3: "ain", Alpha2: "", English: []string{"Ainu"},
		French: []string{"aïnou"}},
	"ak": {Alpha3: "aka", Alpha2: "ak", English: []string{"Akan"},
		French: []string{"akan"}},
	"aka": {Alpha3: "aka", Alpha2: "ak", English: []string{"Akan"},
		French: []string{"akan"}},
	"akk": {Alpha3: "akk", Alpha2: "", English: []string{"Akkadian"},
		French: []string{"akkadien"}},
	"alb": {Alpha3: "alb", Alpha2: "sq", English: []string{"Albanian"},
		French: []string{"albanais"}},
	"ale": {Alpha3: "ale", Alpha2: "", English: []string{"Aleut"},
		French: []string{"aléoute"}},
	"alg": {Alpha3: "alg", Alpha2: "", English: []string{"Algonquian languages"},
		French: []string{"algonquines, langues"}},
	"alt": {Alpha3: "alt", Alpha2: "", English: []string{"Southern Altai"},
		French: []string{"altai du Sud"}},
	"am": {Alpha3: "amh", Alpha2: "am", English: []string{"Amharic"},
		French: []string{"amharique"}},
	"amh": {Alpha3: "amh", Alpha2: "am", English: []string{"Amharic"},
		French: []string{"amharique"}},
	"an": {Alpha3: "arg", Alpha2: "an", English: []string{"Aragonese"},
		French: []string{"aragonais"}},
	"ang": {Alpha3: "ang", Alpha2: "", English: []string{"English, Old (ca.450-1100)"},
		French: []string{"anglo-saxon (ca.450-1100)"}},
	"anp": {Alpha3: "anp", Alpha2: "", English: []string{"Angika"},
		French: []string{"angika"}},
	"apa": {Alpha3: "apa", Alpha2: "", English: []string{"Apache languages"},
		French: []string{"apaches, langues"}},
	"ar": {Alpha3: "ara", Alpha2: "ar", English: []string{"Arabic"},
		French: []string{"arabe"}},
	"ara": {Alpha3: "ara", Alpha2: "ar", English: []string{"Arabic"},
		French: []string{"arabe"}},
	"arc": {Alpha3: "arc", Alpha2: "", English: []string{"Official Aramaic (700-300 BCE)", "Imperial Aramaic (700-300 BCE)"},
		French: []string{"araméen d'empire (700-300 BCE)"}},
	"arg": {Alpha3: "arg", Alpha2: "an", English: []string{"Aragonese"},
		French: []string{"aragonais"}},
	"arm": {Alpha3: "arm", Alpha2: "hy", English: []string{"Armenian"},
		French: []string{"arménien"}},
	"arn": {Alpha3: "arn", Alpha2: "", English: []string{"Mapudungun", "Mapuche"},
		French: []string{"mapudungun", "mapuche", "mapuce"}},
	"arp": {Alpha3: "arp", Alpha2: "", English: []string{"Arapaho"},
		French: []string{"arapaho"}},
	"art": {Alpha3: "art", Alpha2: "", English: []string{"Artificial languages"},
		French: []string{"artificielles, langues"}},
	"arw": {Alpha3: "arw", Alpha2: "", English: []string{"Arawak"},
		French: []string{"arawak"}},
	"as": {Alpha3: "asm", Alpha2: "as", English: []string{"Assamese"},
		French: []string{"assamais"}},
	"asm": {Alpha3: "asm", Alpha2: "as", English: []string{"Assamese"},
		French: []string{"assamais"}},
	"ast": {Alpha3: "ast", Alpha2: "", English: []string{"Asturian", "Bable", "Leonese", "Asturleonese"},
		French: []string{"asturien", "bable", "léonais", "asturoléonais"}},
	"ath": {Alpha3: "ath", Alpha2: "", English: []string{"Athapascan languages"},
		French: []string{"athapascanes, langues"}},
	"aus": {Alpha3: "aus", Alpha2: "", English: []string{"Australian languages"},
		French: []string{"australiennes, langues"}},
	"av": {Alpha3: "ava", Alpha2: "av", English: []string{"Avaric"},
		French: []string{"avar"}},
	"ava": {Alpha3: "ava", Alpha2: "av", English: []string{"Avaric"},
		French: []string{"avar"}},
	"ave": {Alpha3: "ave", Alpha2: "ae", English: []string{"Avestan"},
		French: []string{"avestique"}},
	"awa": {Alpha3: "awa", Alpha2: "", English: []string{"Awadhi"},
		French: []string{"awadhi"}},
	"ay": {Alpha3: "aym", Alpha2: "ay", English: []string{"Aymara"},
		French: []string{"aymara"}},
	"aym": {Alpha3: "aym", Alpha2: "ay", English: []string{"Aymara"},
		French: []string{"aymara"}},
	"az": {Alpha3: "aze", Alpha2: "az", English: []string{"Azerbaijani"},
		French: []string{"azéri"}},
	"aze": {Alpha3: "aze", Alpha2: "az", English: []string{"Azerbaijani"},
		French: []string{"azéri"}},
	"ba": {Alpha3: "bak", Alpha2: "ba", English: []string{"Bashkir"},
		French: []string{"bachkir"}},
	"bad": {Alpha3: "bad", Alpha2: "", English: []string{"Banda languages"},
		French: []string{"banda, langues"}},
	"bai": {Alpha3: "bai", Alpha2: "", English: []string{"Bamileke languages"},
		French: []string{"bamiléké, langues"}},
	"bak": {Alpha3: "bak", Alpha2: "ba", English: []string{"Bashkir"},
		French: []string{"bachkir"}},
	"bal": {Alpha3: "bal", Alpha2: "", English: []string{"Baluchi"},
		French: []string{"baloutchi"}},
	"bam": {Alpha3: "bam", Alpha2: "bm", English: []string{"Bambara"},
		French: []string{"bambara"}},
	"ban": {Alpha3: "ban", Alpha2: "", English: []string{"Balinese"},
		French: []string{"balinais"}},
	"baq": {Alpha3: "baq", Alpha2: "eu", English: []string{"Basque"},
		French: []string{"basque"}},
	"bas": {Alpha3: "bas", Alpha2: "", English: []string{"Basa"},
		French: []string{"basa"}},
	"bat": {Alpha3: "bat", Alpha2: "", English: []string{"Baltic languages"},
		French: []string{"baltes, langues"}},
	"be": {Alpha3: "bel", Alpha2: "be", English: []string{"Belarusian"},
		French: []string{"biélorusse"}},
	"bej": {Alpha3: "bej", Alpha2: "", English: []string{"Beja", "Bedawiyet"},
		French: []string{"bedja"}},
	"bel": {Alpha3: "bel", Alpha2: "be", English: []string{"Belarusian"},
		French: []string{"biélorusse"}},
	"bem": {Alpha3: "bem", Alpha2: "", English: []string{"Bemba"},
		French: []string{"bemba"}},
	"ben": {Alpha3: "ben", Alpha2: "bn", English: []string{"Bengali"},
		French: []string{"bengali"}},
	"ber": {Alpha3: "ber", Alpha2: "", English: []string{"Berber languages"},
		French: []string{"berbères, langues"}},
	"bg": {Alpha3: "bul", Alpha2: "bg", English: []string{"Bulgarian"},
		French: []string{"bulgare"}},
	"bh": {Alpha3: "bih", Alpha2: "bh", English: []string{"Bihari languages"},
		French: []string{"langues biharis"}},
	"bho": {Alpha3: "bho", Alpha2: "", English: []string{"Bhojpuri"},
		French: []string{"bhojpuri"}},
	"bi": {Alpha3: "bis", Alpha2: "bi", English: []string{"Bislama"},
		French: []string{"bichlamar"}},
	"bih": {Alpha3: "bih", Alpha2: "bh", English: []string{"Bihari languages"},
		French: []string{"langues biharis"}},
	"bik": {Alpha3: "bik", Alpha2: "", English: []string{"Bikol"},
		French: []string{"bikol"}},
	"bin": {Alpha3: "bin", Alpha2: "", English: []string{"Bini", "Edo"},
		French: []string{"bini", "edo"}},
	"bis": {Alpha3: "bis", Alpha2: "bi", English: []string{"Bislama"},
		French: []string{"bichlamar"}},
	"bla": {Alpha3: "bla", Alpha2: "", English: []string{"Siksika"},
		French: []string{"blackfoot"}},
	"bm": {Alpha3: "bam", Alpha2: "bm", English: []string{"Bambara"},
		French: []string{"bambara"}},
	"bn": {Alpha3: "ben", Alpha2: "bn", English: []string{"Bengali"},
		French: []string{"bengali"}},
	"bnt": {Alpha3: "bnt", Alpha2: "", English: []string{"Bantu languages"},
		French: []string{"bantou, langues"}},
	"bo": {Alpha3: "tib", Alpha2: "bo", English: []string{"Tibetan"},
		French: []string{"tibétain"}},
	"bos": {Alpha3: "bos", Alpha2: "bs", English: []string{"Bosnian"},
		French: []string{"bosniaque"}},
	"br": {Alpha3: "bre", Alpha2: "br", English: []string{"Breton"},
		French: []string{"breton"}},
	"bra": {Alpha3: "bra", Alpha2: "", English: []string{"Braj"},
		French: []string{"braj"}},
	"bre": {Alpha3: "bre", Alpha2: "br", English: []string{"Breton"},
		French: []string{"breton"}},
	"bs": {Alpha3: "bos", Alpha2: "bs", English: []string{"Bosnian"},
		French: []string{"bosniaque"}},
	"btk": {Alpha3: "btk", Alpha2: "", English: []string{"Batak languages"},
		French: []string{"batak, langues"}},
	"bua": {Alpha3: "bua", Alpha2: "", English: []string{"Buriat"},
		French: []string{"bouriate"}},
	"bug": {Alpha3: "bug", Alpha2: "", English: []string{"Buginese"},
		French: []string{"bugi"}},
	"bul": {Alpha3: "bul", Alpha2: "bg", English: []string{"Bulgarian"},
		French: []string{"bulgare"}},
	"bur": {Alpha3: "bur", Alpha2: "my", English: []string{"Burmese"},
		French: []string{"birman"}},
	"byn": {Alpha3: "byn", Alpha2: "", English: []string{"Blin", "Bilin"},
		French: []string{"blin", "bilen"}},
	"ca": {Alpha3: "cat", Alpha2: "ca", English: []string{"Catalan", "Valencian"},
		French: []string{"catalan", "valencien"}},
	"cad": {Alpha3: "cad", Alpha2: "", English: []string{"Caddo"},
		French: []string{"caddo"}},
	"cai": {Alpha3: "cai", Alpha2: "", English: []string{"Central American Indian languages"},
		French: []string{"amérindiennes de L'Amérique centrale, langues"}},
	"car": {Alpha3: "car", Alpha2: "", English: []string{"Galibi Carib"},
		French: []string{"karib", "galibi", "carib"}},
	"cat": {Alpha3: "cat", Alpha2: "ca", English: []string{"Catalan", "Valencian"},
		French: []string{"catalan", "valencien"}},
	"cau": {Alpha3: "cau", Alpha2: "", English: []string{"Caucasian languages"},
		French: []string{"caucasiennes, langues"}},
	"ce": {Alpha3: "che", Alpha2: "ce", English: []string{"Chechen"},
		French: []string{"tchétchène"}},
	"ceb": {Alpha3: "ceb", Alpha2: "", English: []string{"Cebuano"},
		French: []string{"cebuano"}},
	"cel": {Alpha3: "cel", Alpha2: "", English: []string{"Celtic languages"},
		French: []string{"celtiques, langues", "celtes, langues"}},
	"ch": {Alpha3: "cha", Alpha2: "ch", English: []string{"Chamorro"},
		French: []string{"chamorro"}},
	"cha": {Alpha3: "cha", Alpha2: "ch", English: []string{"Chamorro"},
		French: []string{"chamorro"}},
	"chb": {Alpha3: "chb", Alpha2: "", English: []string{"Chibcha"},
		French: []string{"chibcha"}},
	"che": {Alpha3: "che", Alpha2: "ce", English: []string{"Chechen"},
		French: []string{"tchétchène"}},
	"chg": {Alpha3: "chg", Alpha2: "", English: []string{"Chagatai"},
		French: []string{"djaghataï"}},
	"chi": {Alpha3: "chi", Alpha2: "zh", English: []string{"Chinese"},
		French: []string{"chinois"}},
	"chk": {Alpha3: "chk", Alpha2: "", English: []string{"Chuukese"},
		French: []string{"chuuk"}},
	"chm": {Alpha3: "chm", Alpha2: "", English: []string{"Mari"},
		French: []string{"mari"}},
	"chn": {Alpha3: "chn", Alpha2: "", English: []string{"Chinook jargon"},
		French: []string{"chinook, jargon"}},
	"cho": {Alpha3: "cho", Alpha2: "", English: []string{"Choctaw"},
		French: []string{"choctaw"}},
	"chp": {Alpha3: "chp", Alpha2: "", English: []string{"Chipewyan", "Dene Suline"},
		French: []string{"chipewyan"}},
	"chr": {Alpha3: "chr", Alpha2: "", English: []string{"Cherokee"},
		French: []string{"cherokee"}},
	"chu": {Alpha3: "chu", Alpha2: "cu", English: []string{"Church Slavic", "Old Slavonic", "Church Slavonic", "Old Bulgarian", "Old Church Slavonic"},
		French: []string{"slavon d'église", "vieux slave", "slavon liturgique", "vieux bulgare"}},
	"chv": {Alpha3: "chv", Alpha2: "cv", English: []string{"Chuvash"},
		French: []string{"tchouvache"}},
	"chy": {Alpha3: "chy", Alpha2: "", English: []string{"Cheyenne"},
		French: []string{"cheyenne"}},
	"cmc": {Alpha3: "cmc", Alpha2: "", English: []string{"Chamic languages"},
		French: []string{"chames, langues"}},
	"cnr": {Alpha3: "cnr", Alpha2: "", English: []string{"Montenegrin"},
		French: []string{"monténégrin"}},
	"co": {Alpha3: "cos", Alpha2: "co", English: []string{"Corsican"},
		French: []string{"corse"}},
	"cop": {Alpha3: "cop", Alpha2: "", English: []string{"Coptic"},
		French: []string{"copte"}},
	"cor": {Alpha3: "cor", Alpha2: "kw", English: []string{"Cornish"},
		French: []string{"cornique"}},
	"cos": {Alpha3: "cos", Alpha2: "co", English: []string{"Corsican"},
		French: []string{"corse"}},
	"cpe": {Alpha3: "cpe", Alpha2: "", English: []string{"Creoles and pidgins, English based"},
		French: []string{"créoles et pidgins basés sur l'anglais"}},
	"cpf": {Alpha3: "cpf", Alpha2: "", English: []string{"Creoles and pidgins, French-based"},
		French: []string{"créoles et pidgins basés sur le français"}},
	"cpp": {Alpha3: "cpp", Alpha2: "", English: []string{"Creoles and pidgins, Portuguese-based"},
		French: []string{"créoles et pidgins basés sur le portugais"}},
	"cr": {Alpha3: "cre", Alpha2: "cr", English: []string{"Cree"},
		French: []string{"cree"}},
	"cre": {Alpha3: "cre", Alpha2: "cr", English: []string{"Cree"},
		French: []string{"cree"}},
	"crh": {Alpha3: "crh", Alpha2: "", English: []string{"Crimean Tatar", "Crimean Turkish"},
		French: []string{"tatar de Crimé"}},
	"crp": {Alpha3: "crp", Alpha2: "", English: []string{"Creoles and pidgins"},
		French: []string{"créoles et pidgins"}},
	"cs": {Alpha3: "cze", Alpha2: "cs", English: []string{"Czech"},
		French: []string{"tchèque"}},
	"csb": {Alpha3: "csb", Alpha2: "", English: []string{"Kashubian"},
		French: []string{"kachoube"}},
	"cu": {Alpha3: "chu", Alpha2: "cu", English: []string{"Church Slavic", "Old Slavonic", "Church Slavonic", "Old Bulgarian", "Old Church Slavonic"},
		French: []string{"slavon d'église", "vieux slave", "slavon liturgique", "vieux bulgare"}},
	"cus": {Alpha3: "cus", Alpha2: "", English: []string{"Cushitic languages"},
		French: []string{"couchitiques, langues"}},
	"cv": {Alpha3: "chv", Alpha2: "cv", English: []string{"Chuvash"},
		French: []string{"tchouvache"}},
	"cy": {Alpha3: "wel", Alpha2: "cy", English: []string{"Welsh"},
		French: []string{"gallois"}},
	"cze": {Alpha3: "cze", Alpha2: "cs", English: []string{"Czech"},
		French: []string{"tchèque"}},
	"da": {Alpha3: "dan", Alpha2: "da", English: []string{"Danish"},
		French: []string{"danois"}},
	"dak": {Alpha3: "dak", Alpha2: "", English: []string{"Dakota"},
		French: []string{"dakota"}},
	"dan": {Alpha3: "dan", Alpha2: "da", English: []string{"Danish"},
		French: []string{"danois"}},
	"dar": {Alpha3: "dar", Alpha2: "", English: []string{"Dargwa"},
		French: []string{"dargwa"}},
	"day": {Alpha3: "day", Alpha2: "", English: []string{"Land Dayak languages"},
		French: []string{"dayak, langues"}},
	"de": {Alpha3: "ger", Alpha2: "de", English: []string{"German"},
		French: []string{"allemand"}},
	"del": {Alpha3: "del", Alpha2: "", English: []string{"Delaware"},
		French: []string{"delaware"}},
	"den": {Alpha3: "den", Alpha2: "", English: []string{"Slave (Athapascan)"},
		French: []string{"esclave (athapascan)"}},
	"dgr": {Alpha3: "dgr", Alpha2: "", English: []string{"Dogrib"},
		French: []string{"dogrib"}},
	"din": {Alpha3: "din", Alpha2: "", English: []string{"Dinka"},
		French: []string{"dinka"}},
	"div": {Alpha3: "div", Alpha2: "dv", English: []string{"Divehi", "Dhivehi", "Maldivian"},
		French: []string{"maldivien"}},
	"doi": {Alpha3: "doi", Alpha2: "", English: []string{"Dogri"},
		French: []string{"dogri"}},
	"dra": {Alpha3: "dra", Alpha2: "", English: []string{"Dravidian languages"},
		French: []string{"dravidiennes, langues"}},
	"dsb": {Alpha3: "dsb", Alpha2: "", English: []string{"Lower Sorbian"},
		French: []string{"bas-sorabe"}},
	"dua": {Alpha3: "dua", Alpha2: "", English: []string{"Duala"},
		French: []string{"douala"}},
	"dum": {Alpha3: "dum", Alpha2: "", English: []string{"Dutch, Middle (ca.1050-1350)"},
		French: []string{"néerlandais moyen (ca. 1050-1350)"}},
	"dut": {Alpha3: "dut", Alpha2: "nl", English: []string{"Dutch", "Flemish"},
		French: []string{"néerlandais", "flamand"}},
	"dv": {Alpha3: "div", Alpha2: "dv", English: []string{"Divehi", "Dhivehi", "Maldivian"},
		French: []string{"maldivien"}},
	"dyu": {Alpha3: "dyu", Alpha2: "", English: []string{"Dyula"},
		French: []string{"dioula"}},
	"dz": {Alpha3: "dzo", Alpha2: "dz", English: []string{"Dzongkha"},
		French: []string{"dzongkha"}},
	"dzo": {Alpha3: "dzo", Alpha2: "dz", English: []string{"Dzongkha"},
		French: []string{"dzongkha"}},
	"ee": {Alpha3: "ewe", Alpha2: "ee", English: []string{"Ewe"},
		French: []string{"éwé"}},
	"efi": {Alpha3: "efi", Alpha2: "", English: []string{"Efik"},
		French: []string{"efik"}},
	"egy": {Alpha3: "egy", Alpha2: "", English: []string{"Egyptian (Ancient)"},
		French: []string{"égyptien"}},
	"eka": {Alpha3: "eka", Alpha2: "", English: []string{"Ekajuk"},
		French: []string{"ekajuk"}},
	"el": {Alpha3: "gre", Alpha2: "el", English: []string{"Greek, Modern (1453-)"},
		French: []string{"grec moderne (après 1453)"}},
	"elx": {Alpha3: "elx", Alpha2: "", English: []string{"Elamite"},
		French: []string{"élamite"}},
	"en": {Alpha3: "eng", Alpha2: "en", English: []string{"English"},
		French: []string{"anglais"}},
	"eng": {Alpha3: "eng", Alpha2: "en", English: []string{"English"},
		French: []string{"anglais"}},
	"enm": {Alpha3: "enm", Alpha2: "", English: []string{"English, Middle (1100-1500)"},
		French: []string{"anglais moyen (1100-1500)"}},
	"eo": {Alpha3: "epo", Alpha2: "eo", English: []string{"Esperanto"},
		French: []string{"espéranto"}},
	"epo": {Alpha3: "epo", Alpha2: "eo", English: []string{"Esperanto"},
		French: []string{"espéranto"}},
	"es": {Alpha3: "spa", Alpha2: "es", English: []string{"Spanish", "Castilian"},
		French: []string{"espagnol", "castillan"}},
	"est": {Alpha3: "est", Alpha2: "et", English: []string{"Estonian"},
		French: []string{"estonien"}},
	"et": {Alpha3: "est", Alpha2: "et", English: []string{"Estonian"},
		French: []string{"estonien"}},
	"eu": {Alpha3: "baq", Alpha2: "eu", English: []string{"Basque"},
		French: []string{"basque"}},
	"ewe": {Alpha3: "ewe", Alpha2: "ee", English: []string{"Ewe"},
		French: []string{"éwé"}},
	"ewo": {Alpha3: "ewo", Alpha2: "", English: []string{"Ewondo"},
		French: []string{"éwondo"}},
	"fa": {Alpha3: "per", Alpha2: "fa", English: []string{"Persian"},
		French: []string{"persan"}},
	"fan": {Alpha3: "fan", Alpha2: "", English: []string{"Fang"},
		French: []string{"fang"}},
	"fao": {Alpha3: "fao", Alpha2: "fo", English: []string{"Faroese"},
		French: []string{"féroïen"}},
	"fat": {Alpha3: "fat", Alpha2: "", English: []string{"Fanti"},
		French: []string{"fanti"}},
	"ff": {Alpha3: "ful", Alpha2: "ff", English: []string{"Fulah"},
		French: []string{"peul"}},
	"fi": {Alpha3: "fin", Alpha2: "fi", English: []string{"Finnish"},
		French: []string{"finnois"}},
	"fij": {Alpha3: "fij", Alpha2: "fj", English: []string{"Fijian"},
		French: []string{"fidjien"}},
	"fil": {Alpha3: "fil", Alpha2: "", English: []string{"Filipino", "Pilipino"},
		French: []string{"filipino", "pilipino"}},
	"fin": {Alpha3: "fin", Alpha2: "fi", English: []string{"Finnish"},
		French: []string{"finnois"}},
	"fiu": {Alpha3: "fiu", Alpha2: "", English: []string{"Finno-Ugrian languages"},
		French: []string{"finno-ougriennes, langues"}},
	"fj": {Alpha3: "fij", Alpha2: "fj", English: []string{"Fijian"},
		French: []string{"fidjien"}},
	"fo": {Alpha3: "fao", Alpha2: "fo", English: []string{"Faroese"},
		French: []string{"féroïen"}},
	"fon": {Alpha3: "fon", Alpha2: "", English: []string{"Fon"},
		French: []string{"fon"}},
	"fr": {Alpha3: "fre", Alpha2: "fr", English: []string{"French"},
		French: []string{"français"}},
	"fre": {Alpha3: "fre", Alpha2: "fr", English: []string{"French"},
		French: []string{"français"}},
	"frm": {Alpha3: "frm", Alpha2: "", English: []string{"French, Middle (ca.1400-1600)"},
		French: []string{"français moyen (1400-1600)"}},
	"fro": {Alpha3: "fro", Alpha2: "", English: []string{"French, Old (842-ca.1400)"},
		French: []string{"français ancien (842-ca.1400)"}},
	"frr": {Alpha3: "frr", Alpha2: "", English: []string{"Northern Frisian"},
		French: []string{"frison septentrional"}},
	"frs": {Alpha3: "frs", Alpha2: "", English: []string{"Eastern Frisian"},
		French: []string{"frison oriental"}},
	"fry": {Alpha3: "fry", Alpha2: "fy", English: []string{"Western Frisian"},
		French: []string{"frison occidental"}},
	"ful": {Alpha3: "ful", Alpha2: "ff", English: []string{"Fulah"},
		French: []string{"peul"}},
	"fur": {Alpha3: "fur", Alpha2: "", English: []string{"Friulian"},
		French: []string{"frioulan"}},
	"fy": {Alpha3: "fry", Alpha2: "fy", English: []string{"Western Frisian"},
		French: []string{"frison occidental"}},
	"ga": {Alpha3: "gle", Alpha2: "ga", English: []string{"Irish"},
		French: []string{"irlandais"}},
	"gaa": {Alpha3: "gaa", Alpha2: "", English: []string{"Ga"},
		French: []string{"ga"}},
	"gay": {Alpha3: "gay", Alpha2: "", English: []string{"Gayo"},
		French: []string{"gayo"}},
	"gba": {Alpha3: "gba", Alpha2: "", English: []string{"Gbaya"},
		French: []string{"gbaya"}},
	"gd": {Alpha3: "gla", Alpha2: "gd", English: []string{"Gaelic", "Scottish Gaelic"},
		French: []string{"gaélique", "gaélique écossais"}},
	"gem": {Alpha3: "gem", Alpha2: "", English: []string{"Germanic languages"},
		French: []string{"germaniques, langues"}},
	"geo": {Alpha3: "geo", Alpha2: "ka", English: []string{"Georgian"},
		French: []string{"géorgien"}},
	"ger": {Alpha3: "ger", Alpha2: "de", English: []string{"German"},
		French: []string{"allemand"}},
	"gez": {Alpha3: "gez", Alpha2: "", English: []string{"Geez"},
		French: []string{"guèze"}},
	"gil": {Alpha3: "gil", Alpha2: "", English: []string{"Gilbertese"},
		French: []string{"kiribati"}},
	"gl": {Alpha3: "glg", Alpha2: "gl", English: []string{"Galician"},
		French: []string{"galicien"}},
	"gla": {Alpha3: "gla", Alpha2: "gd", English: []string{"Gaelic", "Scottish Gaelic"},
		French: []string{"gaélique", "gaélique écossais"}},
	"gle": {Alpha3: "gle", Alpha2: "ga", English: []string{"Irish"},
		French: []string{"irlandais"}},
	"glg": {Alpha3: "glg", Alpha2: "gl", English: []string{"Galician"},
		French: []string{"galicien"}},
	"glv": {Alpha3: "glv", Alpha2: "gv", English: []string{"Manx"},
		French: []string{"manx", "mannois"}},
	"gmh": {Alpha3: "gmh", Alpha2: "", English: []string{"German, Middle High (ca.1050-1500)"},
		French: []string{"allemand, moyen haut (ca. 1050-1500)"}},
	"gn": {Alpha3: "grn", Alpha2: "gn", English: []string{"Guarani"},
		French: []string{"guarani"}},
	"goh": {Alpha3: "goh", Alpha2: "", English: []string{"German, Old High (ca.750-1050)"},
		French: []string{"allemand, vieux haut (ca. 750-1050)"}},
	"gon": {Alpha3: "gon", Alpha2: "", English: []string{"Gondi"},
		French: []string{"gond"}},
	"gor": {Alpha3: "gor", Alpha2: "", English: []string{"Gorontalo"},
		French: []string{"gorontalo"}},
	"got": {Alpha3: "got", Alpha2: "", English: []string{"Gothic"},
		French: []string{"gothique"}},
	"grb": {Alpha3: "grb", Alpha2: "", English: []string{"Grebo"},
		French: []string{"grebo"}},
	"grc": {Alpha3: "grc", Alpha2: "", English: []string{"Greek, Ancient (to 1453)"},
		French: []string{"grec ancien (jusqu'à 1453)"}},
	"gre": {Alpha3: "gre", Alpha2: "el", English: []string{"Greek, Modern (1453-)"},
		French: []string{"grec moderne (après 1453)"}},
	"grn": {Alpha3: "grn", Alpha2: "gn", English: []string{"Guarani"},
		French: []string{"guarani"}},
	"gsw": {Alpha3: "gsw", Alpha2: "", English: []string{"Swiss German", "Alemannic", "Alsatian"},
		French: []string{"suisse alémanique", "alémanique", "alsacien"}},
	"gu": {Alpha3: "guj", Alpha2: "gu", English: []string{"Gujarati"},
		French: []string{"goudjrati"}},
	"guj": {Alpha3: "guj", Alpha2: "gu", English: []string{"Gujarati"},
		French: []string{"goudjrati"}},
	"gv": {Alpha3: "glv", Alpha2: "gv", English: []string{"Manx"},
		French: []string{"manx", "mannois"}},
	"gwi": {Alpha3: "gwi", Alpha2: "", English: []string{"Gwich'in"},
		French: []string{"gwich'in"}},
	"ha": {Alpha3: "hau", Alpha2: "ha", English: []string{"Hausa"},
		French: []string{"haoussa"}},
	"hai": {Alpha3: "hai", Alpha2: "", English: []string{"Haida"},
		French: []string{"haida"}},
	"hat": {Alpha3: "hat", Alpha2: "ht", English: []string{"Haitian", "Haitian Creole"},
		French: []string{"haïtien", "créole haïtien"}},
	"hau": {Alpha3: "hau", Alpha2: "ha", English: []string{"Hausa"},
		French: []string{"haoussa"}},
	"haw": {Alpha3: "haw", Alpha2: "", English: []string{"Hawaiian"},
		French: []string{"hawaïen"}},
	"he": {Alpha3: "heb", Alpha2: "he", English: []string{"Hebrew"},
		French: []string{"hébreu"}},
	"heb": {Alpha3: "heb", Alpha2: "he", English: []string{"Hebrew"},
		French: []string{"hébreu"}},
	"her": {Alpha3: "her", Alpha2: "hz", English: []string{"Herero"},
		French: []string{"herero"}},
	"hi": {Alpha3: "hin", Alpha2: "hi", English: []string{"Hindi"},
		French: []string{"hindi"}},
	"hil": {Alpha3: "hil", Alpha2: "", English: []string{"Hiligaynon"},
		French: []string{"hiligaynon"}},
	"him": {Alpha3: "him", Alpha2: "", English: []string{"Himachali languages", "Western Pahari languages"},
		French: []string{"langues himachalis", "langues paharis occidentales"}},
	"hin": {Alpha3: "hin", Alpha2: "hi", English: []string{"Hindi"},
		French: []string{"hindi"}},
	"hit": {Alpha3: "hit", Alpha2: "", English: []string{"Hittite"},
		French: []string{"hittite"}},
	"hmn": {Alpha3: "hmn", Alpha2: "", English: []string{"Hmong", "Mong"},
		French: []string{"hmong"}},
	"hmo": {Alpha3: "hmo", Alpha2: "ho", English: []string{"Hiri Motu"},
		French: []string{"hiri motu"}},
	"ho": {Alpha3: "hmo", Alpha2: "ho", English: []string{"Hiri Motu"},
		French: []string{"hiri motu"}},
	"hr": {Alpha3: "hrv", Alpha2: "hr", English: []string{"Croatian"},
		French: []string{"croate"}},
	"hrv": {Alpha3: "hrv", Alpha2: "hr", English: []string{"Croatian"},
		French: []string{"croate"}},
	"hsb": {Alpha3: "hsb", Alpha2: "", English: []string{"Upper Sorbian"},
		French: []string{"haut-sorabe"}},
	"ht": {Alpha3: "hat", Alpha2: "ht", English: []string{"Haitian", "Haitian Creole"},
		French: []string{"haïtien", "créole haïtien"}},
	"hu": {Alpha3: "hun", Alpha2: "hu", English: []string{"Hungarian"},
		French: []string{"hongrois"}},
	"hun": {Alpha3: "hun", Alpha2: "hu", English: []string{"Hungarian"},
		French: []string{"hongrois"}},
	"hup": {Alpha3: "hup", Alpha2: "", English: []string{"Hupa"},
		French: []string{"hupa"}},
	"hy": {Alpha3: "arm", Alpha2: "hy", English: []string{"Armenian"},
		French: []string{"arménien"}},
	"hz": {Alpha3: "her", Alpha2: "hz", English: []string{"Herero"},
		French: []string{"herero"}},
	"ia": {Alpha3: "ina", Alpha2: "ia", English: []string{"Interlingua (International Auxiliary Language Association)"},
		French: []string{"interlingua (langue auxiliaire internationale)"}},
	"iba": {Alpha3: "iba", Alpha2: "", English: []string{"Iban"},
		French: []string{"iban"}},
	"ibo": {Alpha3: "ibo", Alpha2: "ig", English: []string{"Igbo"},
		French: []string{"igbo"}},
	"ice": {Alpha3: "ice", Alpha2: "is", English: []string{"Icelandic"},
		French: []string{"islandais"}},
	"id": {Alpha3: "ind", Alpha2: "id", English: []string{"Indonesian"},
		French: []string{"indonésien"}},
	"ido": {Alpha3: "ido", Alpha2: "io", English: []string{"Ido"},
		French: []string{"ido"}},
	"ie": {Alpha3: "ile", Alpha2: "ie", English: []string{"Interlingue", "Occidental"},
		French: []string{"interlingue"}},
	"ig": {Alpha3: "ibo", Alpha2: "ig", English: []string{"Igbo"},
		French: []string{"igbo"}},
	"ii": {Alpha3: "iii", Alpha2: "ii", English: []string{"Sichuan Yi", "Nuosu"},
		French: []string{"yi de Sichuan"}},
	"iii": {Alpha3: "iii", Alpha2: "ii", English: []string{"Sichuan Yi", "Nuosu"},
		French: []string{"yi de Sichuan"}},
	"ijo": {Alpha3: "ijo", Alpha2: "", English: []string{"Ijo languages"},
		French: []string{"ijo, langues"}},
	"ik": {Alpha3: "ipk", Alpha2: "ik", English: []string{"Inupiaq"},
		French: []string{"inupiaq"}},
	"iku": {Alpha3: "iku", Alpha2: "iu", English: []string{"Inuktitut"},
		French: []string{"inuktitut"}},
	"ile": {Alpha3: "ile", Alpha2: "ie", English: []string{"Interlingue", "Occidental"},
		French: []string{"interlingue"}},
	"ilo": {Alpha3: "ilo", Alpha2: "", English: []string{"Iloko"},
		French: []string{"ilocano"}},
	"ina": {Alpha3: "ina", Alpha2: "ia", English: []string{"Interlingua (International Auxiliary Language Association)"},
		French: []string{"interlingua (langue auxiliaire internationale)"}},
	"inc": {Alpha3: "inc", Alpha2: "", English: []string{"Indic languages"},
		French: []string{"indo-aryennes, langues"}},
	"ind": {Alpha3: "ind", Alpha2: "id", English: []string{"Indonesian"},
		French: []string{"indonésien"}},
	"ine": {Alpha3: "ine", Alpha2: "", English: []string{"Indo-European languages"},
		French: []string{"indo-européennes, langues"}},
	"inh": {Alpha3: "inh", Alpha2: "", English: []string{"Ingush"},
		French: []string{"ingouche"}},
	"io": {Alpha3: "ido", Alpha2: "io", English: []string{"Ido"},
		French: []string{"ido"}},
	"ipk": {Alpha3: "ipk", Alpha2: "ik", English: []string{"Inupiaq"},
		French: []string{"inupiaq"}},
	"ira": {Alpha3: "ira", Alpha2: "", English: []string{"Iranian languages"},
		French: []string{"iraniennes, langues"}},
	"iro": {Alpha3: "iro", Alpha2: "", English: []string{"Iroquoian languages"},
		French: []string{"iroquoises, langues"}},
	"is": {Alpha3: "ice", Alpha2: "is", English: []string{"Icelandic"},
		French: []string{"islandais"}},
	"it": {Alpha3: "ita", Alpha2: "it", English: []string{"Italian"},
		French: []string{"italien"}},
	"ita": {Alpha3: "ita", Alpha2: "it", English: []string{"Italian"},
		French: []string{"italien"}},
	"iu": {Alpha3: "iku", Alpha2: "iu", English: []string{"Inuktitut"},
		French: []string{"inuktitut"}},
	"ja": {Alpha3: "jpn", Alpha2: "ja", English: []string{"Japanese"},
		French: []string{"japonais"}},
	"jav": {Alpha3: "jav", Alpha2: "jv", English: []string{"Javanese"},
		French: []string{"javanais"}},
	"jbo": {Alpha3: "jbo", Alpha2: "", English: []string{"Lojban"},
		French: []string{"lojban"}},
	"jpn": {Alpha3: "jpn", Alpha2: "ja", English: []string{"Japanese"},
		French: []string{"japonais"}},
	"jpr": {Alpha3: "jpr", Alpha2: "", English: []string{"Judeo-Persian"},
		French: []string{"judéo-persan"}},
	"jrb": {Alpha3: "jrb", Alpha2: "", English: []string{"Judeo-Arabic"},
		French: []string{"judéo-arabe"}},
	"jv": {Alpha3: "jav", Alpha2: "jv", English: []string{"Javanese"},
		French: []string{"javanais"}},
	"ka": {Alpha3: "geo", Alpha2: "ka", English: []string{"Georgian"},
		French: []string{"géorgien"}},
	"kaa": {Alpha3: "kaa", Alpha2: "", English: []string{"Kara-Kalpak"},
		French: []string{"karakalpak"}},
	"kab": {Alpha3: "kab", Alpha2: "", English: []string{"Kabyle"},
		French: []string{"kabyle"}},
	"kac": {Alpha3: "kac", Alpha2: "", English: []string{"Kachin", "Jingpho"},
		French: []string{"kachin", "jingpho"}},
	"kal": {Alpha3: "kal", Alpha2: "kl", English: []string{"Kalaallisut", "Greenlandic"},
		French: []string{"groenlandais"}},
	"kam": {Alpha3: "kam", Alpha2: "", English: []string{"Kamba"},
		French: []string{"kamba"}},
	"kan": {Alpha3: "kan", Alpha2: "kn", English: []string{"Kannada"},
		French: []string{"kannada"}},
	"kar": {Alpha3: "kar", Alpha2: "", English: []string{"Karen languages"},
		French: []string{"karen, langues"}},
	"kas": {Alpha3: "kas", Alpha2: "ks", English: []string{"Kashmiri"},
		French: []string{"kashmiri"}},
	"kau": {Alpha3: "kau", Alpha2: "kr", English: []string{"Kanuri"},
		French: []string{"kanouri"}},
	"kaw": {Alpha3: "kaw", Alpha2: "", English: []string{"Kawi"},
		French: []string{"kawi"}},
	"kaz": {Alpha3: "kaz", Alpha2: "kk", English: []string{"Kazakh"},
		French: []string{"kazakh"}},
	"kbd": {Alpha3: "kbd", Alpha2: "", English: []string{"Kabardian"},
		French: []string{"kabardien"}},
	"kg": {Alpha3: "kon", Alpha2: "kg", English: []string{"Kongo"},
		French: []string{"kongo"}},
	"kha": {Alpha3: "kha", Alpha2: "", English: []string{"Khasi"},
		French: []string{"khasi"}},
	"khi": {Alpha3: "khi", Alpha2: "", English: []string{"Khoisan languages"},
		French: []string{"khoïsan, langues"}},
	"khm": {Alpha3: "khm", Alpha2: "km", English: []string{"Central Khmer"},
		French: []string{"khmer central"}},
	"kho": {Alpha3: "kho", Alpha2: "", English: []string{"Khotanese", "Sakan"},
		French: []string{"khotanais", "sakan"}},
	"ki": {Alpha3: "kik", Alpha2: "ki", English: []string{"Kikuyu", "Gikuyu"},
		French: []string{"kikuyu"}},
	"kik": {Alpha3: "kik", Alpha2: "ki", English: []string{"Kikuyu", "Gikuyu"},
		French: []string{"kikuyu"}},
	"kin": {Alpha3: "kin", Alpha2: "rw", English: []string{"Kinyarwanda"},
		French: []string{"rwanda"}},
	"kir": {Alpha3: "kir", Alpha2: "ky", English: []string{"Kirghiz", "Kyrgyz"},
		French: []string{"kirghiz"}},
	"kj": {Alpha3: "kua", Alpha2: "kj", English: []string{"Kuanyama", "Kwanyama"},
		French: []string{"kuanyama", "kwanyama"}},
	"kk": {Alpha3: "kaz", Alpha2: "kk", English: []string{"Kazakh"},
		French: []string{"kazakh"}},
	"kl": {Alpha3: "kal", Alpha2: "kl", English: []string{"Kalaallisut", "Greenlandic"},
		French: []string{"groenlandais"}},
	"km": {Alpha3: "khm", Alpha2: "km", English: []string{"Central Khmer"},
		French: []string{"khmer central"}},
	"kmb": {Alpha3: "kmb", Alpha2: "", English: []string{"Kimbundu"},
		French: []string{"kimbundu"}},
	"kn": {Alpha3: "kan", Alpha2: "kn", English: []string{"Kannada"},
		French: []string{"kannada"}},
	"ko": {Alpha3: "kor", Alpha2: "ko", English: []string{"Korean"},
		French: []string{"coréen"}},
	"kok": {Alpha3: "kok", Alpha2: "", English: []string{"Konkani"},
		French: []string{"konkani"}},
	"kom": {Alpha3: "kom", Alpha2: "kv", English: []string{"Komi"},
		French: []string{"kom"}},
	"kon": {Alpha3: "kon", Alpha2: "kg", English: []string{"Kongo"},
		French: []string{"kongo"}},
	"kor": {Alpha3: "kor", Alpha2: "ko", English: []string{"Korean"},
		French: []string{"coréen"}},
	"kos": {Alpha3: "kos", Alpha2: "", English: []string{"Kosraean"},
		French: []string{"kosrae"}},
	"kpe": {Alpha3: "kpe", Alpha2: "", English: []string{"Kpelle"},
		French: []string{"kpellé"}},
	"kr": {Alpha3: "kau", Alpha2: "kr", English: []string{"Kanuri"},
		French: []string{"kanouri"}},
	"krc": {Alpha3: "krc", Alpha2: "", English: []string{"Karachay-Balkar"},
		French: []string{"karatchai balkar"}},
	"krl": {Alpha3: "krl", Alpha2: "", English: []string{"Karelian"},
		French: []string{"carélien"}},
	"kro": {Alpha3: "kro", Alpha2: "", English: []string{"Kru languages"},
		French: []string{"krou, langues"}},
	"kru": {Alpha3: "kru", Alpha2: "", English: []string{"Kurukh"},
		French: []string{"kurukh"}},
	"ks": {Alpha3: "kas", Alpha2: "ks", English: []string{"Kashmiri"},
		French: []string{"kashmiri"}},
	"ku": {Alpha3: "kur", Alpha2: "ku", English: []string{"Kurdish"},
		French: []string{"kurde"}},
	"kua": {Alpha3: "kua", Alpha2: "kj", English: []string{"Kuanyama", "Kwanyama"},
		French: []string{"kuanyama", "kwanyama"}},
	"kum": {Alpha3: "kum", Alpha2: "", English: []string{"Kumyk"},
		French: []string{"koumyk"}},
	"kur": {Alpha3: "kur", Alpha2: "ku", English: []string{"Kurdish"},
		French: []string{"kurde"}},
	"kut": {Alpha3: "kut", Alpha2: "", English: []string{"Kutenai"},
		French: []string{"kutenai"}},
	"kv": {Alpha3: "kom", Alpha2: "kv", English: []string{"Komi"},
		French: []string{"kom"}},
	"kw": {Alpha3: "cor", Alpha2: "kw", English: []string{"Cornish"},
		French: []string{"cornique"}},
	"ky": {Alpha3: "kir", Alpha2: "ky", English: []string{"Kirghiz", "Kyrgyz"},
		French: []string{"kirghiz"}},
	"la": {Alpha3: "lat", Alpha2: "la", English: []string{"Latin"},
		French: []string{"latin"}},
	"lad": {Alpha3: "lad", Alpha2: "", English: []string{"Ladino"},
		French: []string{"judéo-espagnol"}},
	"lah": {Alpha3: "lah", Alpha2: "", English: []string{"Lahnda"},
		French: []string{"lahnda"}},
	"lam": {Alpha3: "lam", Alpha2: "", English: []string{"Lamba"},
		French: []string{"lamba"}},
	"lao": {Alpha3: "lao", Alpha2: "lo", English: []string{"Lao"},
		French: []string{"lao"}},
	"lat": {Alpha3: "lat", Alpha2: "la", English: []string{"Latin"},
		French: []string{"latin"}},
	"lav": {Alpha3: "lav", Alpha2: "lv", English: []string{"Latvian"},
		French: []string{"letton"}},
	"lb": {Alpha3: "ltz", Alpha2: "lb", English: []string{"Luxembourgish", "Letzeburgesch"},
		French: []string{"luxembourgeois"}},
	"lez": {Alpha3: "lez", Alpha2: "", English: []string{"Lezghian"},
		French: []string{"lezghien"}},
	"lg": {Alpha3: "lug", Alpha2: "lg", English: []string{"Ganda"},
		French: []string{"ganda"}},
	"li": {Alpha3: "lim", Alpha2: "li", English: []string{"Limburgan", "Limburger", "Limburgish"},
		French: []string{"limbourgeois"}},
	"lim": {Alpha3: "lim", Alpha2: "li", English: []string{"Limburgan", "Limburger", "Limburgish"},
		French: []string{"limbourgeois"}},
	"lin": {Alpha3: "lin", Alpha2: "ln", English: []string{"Lingala"},
		French: []string{"lingala"}},
	"lit": {Alpha3: "lit", Alpha2: "lt", English: []string{"Lithuanian"},
		French: []string{"lituanien"}},
	"ln": {Alpha3: "lin", Alpha2: "ln", English: []string{"Lingala"},
		French: []string{"lingala"}},
	"lo": {Alpha3: "lao", Alpha2: "lo", English: []string{"Lao"},
		French: []string{"lao"}},
	"lol": {Alpha3: "lol", Alpha2: "", English: []string{"Mongo"},
		French: []string{"mongo"}},
	"loz": {Alpha3: "loz", Alpha2: "", English: []string{"Lozi"},
		French: []string{"lozi"}},
	"lt": {Alpha3: "lit", Alpha2: "lt", English: []string{"Lithuanian"},
		French: []string{"lituanien"}},
	"ltz": {Alpha3: "ltz", Alpha2: "lb", English: []string{"Luxembourgish", "Letzeburgesch"},
		French: []string{"luxembourgeois"}},
	"lu": {Alpha3: "lub", Alpha2: "lu", English: []string{"Luba-Katanga"},
		French: []string{"luba-katanga"}},
	"lua": {Alpha3: "lua", Alpha2: "", English: []string{"Luba-Lulua"},
		French: []string{"luba-lulua"}},
	"lub": {Alpha3: "lub", Alpha2: "lu", English: []string{"Luba-Katanga"},
		French: []string{"luba-katanga"}},
	"lug": {Alpha3: "lug", Alpha2: "lg", English: []string{"Ganda"},
		French: []string{"ganda"}},
	"lui": {Alpha3: "lui", Alpha2: "", English: []string{"Luiseno"},
		French: []string{"luiseno"}},
	"lun": {Alpha3: "lun", Alpha2: "", English: []string{"Lunda"},
		French: []string{"lunda"}},
	"luo": {Alpha3: "luo", Alpha2: "", English: []string{"Luo (Kenya and Tanzania)"},
		French: []string{"luo (Kenya et Tanzanie)"}},
	"lus": {Alpha3: "lus", Alpha2: "", English: []string{"Lushai"},
		French: []string{"lushai"}},
	"lv": {Alpha3: "lav", Alpha2: "lv", English: []string{"Latvian"},
		French: []string{"letton"}},
	"mac": {Alpha3: "mac", Alpha2: "mk", English: []string{"Macedonian"},
		French: []string{"macédonien"}},
	"mad": {Alpha3: "mad", Alpha2: "", English: []string{"Madurese"},
		French: []string{"madourais"}},
	"mag": {Alpha3: "mag", Alpha2: "", English: []string{"Magahi"},
		French: []string{"magahi"}},
	"mah": {Alpha3: "mah", Alpha2: "mh", English: []string{"Marshallese"},
		French: []string{"marshall"}},
	"mai": {Alpha3: "mai", Alpha2: "", English: []string{"Maithili"},
		French: []string{"maithili"}},
	"mak": {Alpha3: "mak", Alpha2: "", English: []string{"Makasar"},
		French: []string{"makassar"}},
	"mal": {Alpha3: "mal", Alpha2: "ml", English: []string{"Malayalam"},
		French: []string{"malayalam"}},
	"man": {Alpha3: "man", Alpha2: "", English: []string{"Mandingo"},
		French: []string{"mandingue"}},
	"mao": {Alpha3: "mao", Alpha2: "mi", English: []string{"Maori"},
		French: []string{"maori"}},
	"map": {Alpha3: "map", Alpha2: "", English: []string{"Austronesian languages"},
		French: []string{"austronésiennes, langues"}},
	"mar": {Alpha3: "mar", Alpha2: "mr", English: []string{"Marathi"},
		French: []string{"marathe"}},
	"mas": {Alpha3: "mas", Alpha2: "", English: []string{"Masai"},
		French: []string{"massaï"}},
	"may": {Alpha3: "may", Alpha2: "ms", English: []string{"Malay"},
		French: []string{"malais"}},
	"mdf": {Alpha3: "mdf", Alpha2: "", English: []string{"Moksha"},
		French: []string{"moksa"}},
	"mdr": {Alpha3: "mdr", Alpha2: "", English: []string{"Mandar"},
		French: []string{"mandar"}},
	"men": {Alpha3: "men", Alpha2: "", English: []string{"Mende"},
		French: []string{"mendé"}},
	"mg": {Alpha3: "mlg", Alpha2: "mg", English: []string{"Malagasy"},
		French: []string{"malgache"}},
	"mga": {Alpha3: "mga", Alpha2: "", English: []string{"Irish, Middle (900-1200)"},
		French: []string{"irlandais moyen (900-1200)"}},
	"mh": {Alpha3: "mah", Alpha2: "mh", English: []string{"Marshallese"},
		French: []string{"marshall"}},
	"mi": {Alpha3: "mao", Alpha2: "mi", English: []string{"Maori"},
		French: []string{"maori"}},
	"mic": {Alpha3: "mic", Alpha2: "", English: []string{"Mi'kmaq", "Micmac"},
		French: []string{"mi'kmaq", "micmac"}},
	"min": {Alpha3: "min", Alpha2: "", English: []string{"Minangkabau"},
		French: []string{"minangkabau"}},
	"mis": {Alpha3: "mis", Alpha2: "", English: []string{"Uncoded languages"},
		French: []string{"langues non codées"}},
	"mk": {Alpha3: "mac", Alpha2: "mk", English: []string{"Macedonian"},
		French: []string{"macédonien"}},
	"mkh": {Alpha3: "mkh", Alpha2: "", English: []string{"Mon-Khmer languages"},
		French: []string{"môn-khmer, langues"}},
	"ml": {Alpha3: "mal", Alpha2: "ml", English: []string{"Malayalam"},
		French: []string{"malayalam"}},
	"mlg": {Alpha3: "mlg", Alpha2: "mg", English: []string{"Malagasy"},
		French: []string{"malgache"}},
	"mlt": {Alpha3: "mlt", Alpha2: "mt", English: []string{"Maltese"},
		French: []string{"maltais"}},
	"mn": {Alpha3: "mon", Alpha2: "mn", English: []string{"Mongolian"},
		French: []string{"mongol"}},
	"mnc": {Alpha3: "mnc", Alpha2: "", English: []string{"Manchu"},
		French: []string{"mandchou"}},
	"mni": {Alpha3: "mni", Alpha2: "", English: []string{"Manipuri"},
		French: []string{"manipuri"}},
	"mno": {Alpha3: "mno", Alpha2: "", English: []string{"Manobo languages"},
		French: []string{"manobo, langues"}},
	"moh": {Alpha3: "moh", Alpha2: "", English: []string{"Mohawk"},
		French: []string{"mohawk"}},
	"mon": {Alpha3: "mon", Alpha2: "mn", English: []string{"Mongolian"},
		French: []string{"mongol"}},
	"mos": {Alpha3: "mos", Alpha2: "", English: []string{"Mossi"},
		French: []string{"moré"}},
	"mr": {Alpha3: "mar", Alpha2: "mr", English: []string{"Marathi"},
		French: []string{"marathe"}},
	"ms": {Alpha3: "may", Alpha2: "ms", English: []string{"Malay"},
		French: []string{"malais"}},
	"mt": {Alpha3: "mlt", Alpha2: "mt", English: []string{"Maltese"},
		French: []string{"maltais"}},
	"mul": {Alpha3: "mul", Alpha2: "", English: []string{"Multiple languages"},
		French: []string{"multilingue"}},
	"mun": {Alpha3: "mun", Alpha2: "", English: []string{"Munda languages"},
		French: []string{"mounda, langues"}},
	"mus": {Alpha3: "mus", Alpha2: "", English: []string{"Creek"},
		French: []string{"muskogee"}},
	"mwl": {Alpha3: "mwl", Alpha2: "", English: []string{"Mirandese"},
		French: []string{"mirandais"}},
	"mwr": {Alpha3: "mwr", Alpha2: "", English: []string{"Marwari"},
		French: []string{"marvari"}},
	"my": {Alpha3: "bur", Alpha2: "my", English: []string{"Burmese"},
		French: []string{"birman"}},
	"myn": {Alpha3: "myn", Alpha2: "", English: []string{"Mayan languages"},
		French: []string{"maya, langues"}},
	"myv": {Alpha3: "myv", Alpha2: "", English: []string{"Erzya"},
		French: []string{"erza"}},
	"na": {Alpha3: "nau", Alpha2: "na", English: []string{"Nauru"},
		French: []string{"nauruan"}},
	"nah": {Alpha3: "nah", Alpha2: "", English: []string{"Nahuatl languages"},
		French: []string{"nahuatl, langues"}},
	"nai": {Alpha3: "nai", Alpha2: "", English: []string{"North American Indian languages"},
		French: []string{"nord-amérindiennes, langues"}},
	"nap": {Alpha3: "nap", Alpha2: "", English: []string{"Neapolitan"},
		French: []string{"napolitain"}},
	"nau": {Alpha3: "nau", Alpha2: "na", English: []string{"Nauru"},
		French: []string{"nauruan"}},
	"nav": {Alpha3: "nav", Alpha2: "nv", English: []string{"Navajo", "Navaho"},
		French: []string{"navaho"}},
	"nb": {Alpha3: "nob", Alpha2: "nb", English: []string{"Bokmål, Norwegian", "Norwegian Bokmål"},
		French: []string{"norvégien bokmål"}},
	"nbl": {Alpha3: "nbl", Alpha2: "nr", English: []string{"Ndebele, South", "South Ndebele"},
		French: []string{"ndébélé du Sud"}},
	"nd": {Alpha3: "nde", Alpha2: "nd", English: []string{"Ndebele, North", "North Ndebele"},
		French: []string{"ndébélé du Nord"}},
	"nde": {Alpha3: "nde", Alpha2: "nd", English: []string{"Ndebele, North", "North Ndebele"},
		French: []string{"ndébélé du Nord"}},
	"ndo": {Alpha3: "ndo", Alpha2: "ng", English: []string{"Ndonga"},
		French: []string{"ndonga"}},
	"nds": {Alpha3: "nds", Alpha2: "", English: []string{"Low German", "Low Saxon", "German, Low", "Saxon, Low"},
		French: []string{"bas allemand", "bas saxon", "allemand, bas", "saxon, bas"}},
	"ne": {Alpha3: "nep", Alpha2: "ne", English: []string{"Nepali"},
		French: []string{"népalais"}},
	"nep": {Alpha3: "nep", Alpha2: "ne", English: []string{"Nepali"},
		French: []string{"népalais"}},
	"new": {Alpha3: "new", Alpha2: "", English: []string{"Nepal Bhasa", "Newari"},
		French: []string{"nepal bhasa", "newari"}},
	"ng": {Alpha3: "ndo", Alpha2: "ng", English: []string{"Ndonga"},
		French: []string{"ndonga"}},
	"nia": {Alpha3: "nia", Alpha2: "", English: []string{"Nias"},
		French: []string{"nias"}},
	"nic": {Alpha3: "nic", Alpha2: "", English: []string{"Niger-Kordofanian languages"},
		French: []string{"nigéro-kordofaniennes, langues"}},
	"niu": {Alpha3: "niu", Alpha2: "", English: []string{"Niuean"},
		French: []string{"niué"}},
	"nl": {Alpha3: "dut", Alpha2: "nl", English: []string{"Dutch", "Flemish"},
		French: []string{"néerlandais", "flamand"}},
	"nn": {Alpha3: "nno", Alpha2: "nn", English: []string{"Norwegian Nynorsk", "Nynorsk, Norwegian"},
		French: []string{"norvégien nynorsk", "nynorsk, norvégien"}},
	"nno": {Alpha3: "nno", Alpha2: "nn", English: []string{"Norwegian Nynorsk", "Nynorsk, Norwegian"},
		French: []string{"norvégien nynorsk", "nynorsk, norvégien"}},
	"no": {Alpha3: "nor", Alpha2: "no", English: []string{"Norwegian"},
		French: []string{"norvégien"}},
	"nob": {Alpha3: "nob", Alpha2: "nb", English: []string{"Bokmål, Norwegian", "Norwegian Bokmål"},
		French: []string{"norvégien bokmål"}},
	"nog": {Alpha3: "nog", Alpha2: "", English: []string{"Nogai"},
		French: []string{"nogaï", "nogay"}},
	"non": {Alpha3: "non", Alpha2: "", English: []string{"Norse, Old"},
		French: []string{"norrois, vieux"}},
	"nor": {Alpha3: "nor", Alpha2: "no", English: []string{"Norwegian"},
		French: []string{"norvégien"}},
	"nqo": {Alpha3: "nqo", Alpha2: "", English: []string{"N'Ko"},
		French: []string{"n'ko"}},
	"nr": {Alpha3: "nbl", Alpha2: "nr", English: []string{"Ndebele, South", "South Ndebele"},
		French: []string{"ndébélé du Sud"}},
	"nso": {Alpha3: "nso", Alpha2: "", English: []string{"Pedi", "Sepedi", "Northern Sotho"},
		French: []string{"pedi", "sepedi", "sotho du Nord"}},
	"nub": {Alpha3: "nub", Alpha2: "", English: []string{"Nubian languages"},
		French: []string{"nubiennes, langues"}},
	"nv": {Alpha3: "nav", Alpha2: "nv", English: []string{"Navajo", "Navaho"},
		French: []string{"navaho"}},
	"nwc": {Alpha3: "nwc", Alpha2: "", English: []string{"Classical Newari", "Old Newari", "Classical Nepal Bhasa"},
		French: []string{"newari classique"}},
	"ny": {Alpha3: "nya", Alpha2: "ny", English: []string{"Chichewa", "Chewa", "Nyanja"},
		French: []string{"chichewa", "chewa", "nyanja"}},
	"nya": {Alpha3: "nya", Alpha2: "ny", English: []string{"Chichewa", "Chewa", "Nyanja"},
		French: []string{"chichewa", "chewa", "nyanja"}},
	"nym": {Alpha3: "nym", Alpha2: "", English: []string{"Nyamwezi"},
		French: []string{"nyamwezi"}},
	"nyn": {Alpha3: "nyn", Alpha2: "", English: []string{"Nyankole"},
		French: []string{"nyankolé"}},
	"nyo": {Alpha3: "nyo", Alpha2: "", English: []string{"Nyoro"},
		French: []string{"nyoro"}},
	"nzi": {Alpha3: "nzi", Alpha2: "", English: []string{"Nzima"},
		French: []string{"nzema"}},
	"oc": {Alpha3: "oci", Alpha2: "oc", English: []string{"Occitan (post 1500)"},
		French: []string{"occitan (après 1500)"}},
	"oci": {Alpha3: "oci", Alpha2: "oc", English: []string{"Occitan (post 1500)"},
		French: []string{"occitan (après 1500)"}},
	"oj": {Alpha3: "oji", Alpha2: "oj", English: []string{"Ojibwa"},
		French: []string{"ojibwa"}},
	"oji": {Alpha3: "oji", Alpha2: "oj", English: []string{"Ojibwa"},
		French: []string{"ojibwa"}},
	"om": {Alpha3: "orm", Alpha2: "om", English: []string{"Oromo"},
		French: []string{"galla"}},
	"or": {Alpha3: "ori", Alpha2: "or", English: []string{"Oriya"},
		French: []string{"oriya"}},
	"ori": {Alpha3: "ori", Alpha2: "or", English: []string{"Oriya"},
		French: []string{"oriya"}},
	"orm": {Alpha3: "orm", Alpha2: "om", English: []string{"Oromo"},
		French: []string{"galla"}},
	"os": {Alpha3: "oss", Alpha2: "os", English: []string{"Ossetian", "Ossetic"},
		French: []string{"ossète"}},
	"osa": {Alpha3: "osa", Alpha2: "", English: []string{"Osage"},
		French: []string{"osage"}},
	"oss": {Alpha3: "oss", Alpha2: "os", English: []string{"Ossetian", "Ossetic"},
		French: []string{"ossète"}},
	"ota": {Alpha3: "ota", Alpha2: "", English: []string{"Turkish, Ottoman (1500-1928)"},
		French: []string{"turc ottoman (1500-1928)"}},
	"oto": {Alpha3: "oto", Alpha2: "", English: []string{"Otomian languages"},
		French: []string{"otomi, langues"}},
	"pa": {Alpha3: "pan", Alpha2: "pa", English: []string{"Panjabi", "Punjabi"},
		French: []string{"pendjabi"}},
	"paa": {Alpha3: "paa", Alpha2: "", English: []string{"Papuan languages"},
		French: []string{"papoues, langues"}},
	"pag": {Alpha3: "pag", Alpha2: "", English: []string{"Pangasinan"},
		French: []string{"pangasinan"}},
	"pal": {Alpha3: "pal", Alpha2: "", English: []string{"Pahlavi"},
		French: []string{"pahlavi"}},
	"pam": {Alpha3: "pam", Alpha2: "", English: []string{"Pampanga", "Kapampangan"},
		French: []string{"pampangan"}},
	"pan": {Alpha3: "pan", Alpha2: "pa", English: []string{"Panjabi", "Punjabi"},
		French: []string{"pendjabi"}},
	"pap": {Alpha3: "pap", Alpha2: "", English: []string{"Papiamento"},
		French: []string{"papiamento"}},
	"pau": {Alpha3: "pau", Alpha2: "", English: []string{"Palauan"},
		French: []string{"palau"}},
	"peo": {Alpha3: "peo", Alpha2: "", English: []string{"Persian, Old (ca.600-400 B.C.)"},
		French: []string{"perse, vieux (ca. 600-400 av. J.-C.)"}},
	"per": {Alpha3: "per", Alpha2: "fa", English: []string{"Persian"},
		French: []string{"persan"}},
	"phi": {Alpha3: "phi", Alpha2: "", English: []string{"Philippine languages"},
		French: []string{"philippines, langues"}},
	"phn": {Alpha3: "phn", Alpha2: "", English: []string{"Phoenician"},
		French: []string{"phénicien"}},
	"pi": {Alpha3: "pli", Alpha2: "pi", English: []string{"Pali"},
		French: []string{"pali"}},
	"pl": {Alpha3: "pol", Alpha2: "pl", English: []string{"Polish"},
		French: []string{"polonais"}},
	"pli": {Alpha3: "pli", Alpha2: "pi", English: []string{"Pali"},
		French: []string{"pali"}},
	"pol": {Alpha3: "pol", Alpha2: "pl", English: []string{"Polish"},
		French: []string{"polonais"}},
	"pon": {Alpha3: "pon", Alpha2: "", English: []string{"Pohnpeian"},
		French: []string{"pohnpei"}},
	"por": {Alpha3: "por", Alpha2: "pt", English: []string{"Portuguese"},
		French: []string{"portugais"}},
	"pra": {Alpha3: "pra", Alpha2: "", English: []string{"Prakrit languages"},
		French: []string{"prâkrit, langues"}},
	"pro": {Alpha3: "pro", Alpha2: "", English: []string{"Provençal, Old (to 1500)", "Occitan, Old (to 1500)"},
		French: []string{"provençal ancien (jusqu'à 1500)", "occitan ancien (jusqu'à 1500)"}},
	"ps": {Alpha3: "pus", Alpha2: "ps", English: []string{"Pushto", "Pashto"},
		French: []string{"pachto"}},
	"pt": {Alpha3: "por", Alpha2: "pt", English: []string{"Portuguese"},
		French: []string{"portugais"}},
	"pus": {Alpha3: "pus", Alpha2: "ps", English: []string{"Pushto", "Pashto"},
		French: []string{"pachto"}},
	"qaa-qtz": {Alpha3: "qaa-qtz", Alpha2: "", English: []string{"Reserved for local use"},
		French: []string{"réservée à l'usage local"}},
	"qu": {Alpha3: "que", Alpha2: "qu", English: []string{"Quechua"},
		French: []string{"quechua"}},
	"que": {Alpha3: "que", Alpha2: "qu", English: []string{"Quechua"},
		French: []string{"quechua"}},
	"raj": {Alpha3: "raj", Alpha2: "", English: []string{"Rajasthani"},
		French: []string{"rajasthani"}},
	"rap": {Alpha3: "rap", Alpha2: "", English: []string{"Rapanui"},
		French: []string{"rapanui"}},
	"rar": {Alpha3: "rar", Alpha2: "", English: []string{"Rarotongan", "Cook Islands Maori"},
		French: []string{"rarotonga", "maori des îles Cook"}},
	"rm": {Alpha3: "roh", Alpha2: "rm", English: []string{"Romansh"},
		French: []string{"romanche"}},
	"rn": {Alpha3: "run", Alpha2: "rn", English: []string{"Rundi"},
		French: []string{"rundi"}},
	"ro": {Alpha3: "rum", Alpha2: "ro", English: []string{"Romanian", "Moldavian", "Moldovan"},
		French: []string{"roumain", "moldave"}},
	"roa": {Alpha3: "roa", Alpha2: "", English: []string{"Romance languages"},
		French: []string{"romanes, langues"}},
	"roh": {Alpha3: "roh", Alpha2: "rm", English: []string{"Romansh"},
		French: []string{"romanche"}},
	"rom": {Alpha3: "rom", Alpha2: "", English: []string{"Romany"},
		French: []string{"tsigane"}},
	"ru": {Alpha3: "rus", Alpha2: "ru", English: []string{"Russian"},
		French: []string{"russe"}},
	"rum": {Alpha3: "rum", Alpha2: "ro", English: []string{"Romanian", "Moldavian", "Moldovan"},
		French: []string{"roumain", "moldave"}},
	"run": {Alpha3: "run", Alpha2: "rn", English: []string{"Rundi"},
		French: []string{"rundi"}},
	"rup": {Alpha3: "rup", Alpha2: "", English: []string{"Aromanian", "Arumanian", "Macedo-Romanian"},
		French: []string{"aroumain", "macédo-roumain"}},
	"rus": {Alpha3: "rus", Alpha2: "ru", English: []string{"Russian"},
		French: []string{"russe"}},
	"rw": {Alpha3: "kin", Alpha2: "rw", English: []string{"Kinyarwanda"},
		French: []string{"rwanda"}},
	"sa": {Alpha3: "san", Alpha2: "sa", English: []string{"Sanskrit"},
		French: []string{"sanskrit"}},
	"sad": {Alpha3: "sad", Alpha2: "", English: []string{"Sandawe"},
		French: []string{"sandawe"}},
	"sag": {Alpha3: "sag", Alpha2: "sg", English: []string{"Sango"},
		French: []string{"sango"}},
	"sah": {Alpha3: "sah", Alpha2: "", English: []string{"Yakut"},
		French: []string{"iakoute"}},
	"sai": {Alpha3: "sai", Alpha2: "", English: []string{"South American Indian languages"},
		French: []string{"sud-amérindiennes, langues"}},
	"sal": {Alpha3: "sal", Alpha2: "", English: []string{"Salishan languages"},
		French: []string{"salishennes, langues"}},
	"sam": {Alpha3: "sam", Alpha2: "", English: []string{"Samaritan Aramaic"},
		French: []string{"samaritain"}},
	"san": {Alpha3: "san", Alpha2: "sa", English: []string{"Sanskrit"},
		French: []string{"sanskrit"}},
	"sas": {Alpha3: "sas", Alpha2: "", English: []string{"Sasak"},
		French: []string{"sasak"}},
	"sat": {Alpha3: "sat", Alpha2: "", English: []string{"Santali"},
		French: []string{"santal"}},
	"sc": {Alpha3: "srd", Alpha2: "sc", English: []string{"Sardinian"},
		French: []string{"sarde"}},
	"scn": {Alpha3: "scn", Alpha2: "", English: []string{"Sicilian"},
		French: []string{"sicilien"}},
	"sco": {Alpha3: "sco", Alpha2: "", English: []string{"Scots"},
		French: []string{"écossais"}},
	"sd": {Alpha3: "snd", Alpha2: "sd", English: []string{"Sindhi"},
		French: []string{"sindhi"}},
	"se": {Alpha3: "sme", Alpha2: "se", English: []string{"Northern Sami"},
		French: []string{"sami du Nord"}},
	"sel": {Alpha3: "sel", Alpha2: "", English: []string{"Selkup"},
		French: []string{"selkoupe"}},
	"sem": {Alpha3: "sem", Alpha2: "", English: []string{"Semitic languages"},
		French: []string{"sémitiques, langues"}},
	"sg": {Alpha3: "sag", Alpha2: "sg", English: []string{"Sango"},
		French: []string{"sango"}},
	"sga": {Alpha3: "sga", Alpha2: "", English: []string{"Irish, Old (to 900)"},
		French: []string{"irlandais ancien (jusqu'à 900)"}},
	"sgn": {Alpha3: "sgn", Alpha2: "", English: []string{"Sign Languages"},
		French: []string{"langues des signes"}},
	"shn": {Alpha3: "shn", Alpha2: "", English: []string{"Shan"},
		French: []string{"chan"}},
	"si": {Alpha3: "sin", Alpha2: "si", English: []string{"Sinhala", "Sinhalese"},
		French: []string{"singhalais"}},
	"sid": {Alpha3: "sid", Alpha2: "", English: []string{"Sidamo"},
		French: []string{"sidamo"}},
	"sin": {Alpha3: "sin", Alpha2: "si", English: []string{"Sinhala", "Sinhalese"},
		French: []string{"singhalais"}},
	"sio": {Alpha3: "sio", Alpha2: "", English: []string{"Siouan languages"},
		French: []string{"sioux, langues"}},
	"sit": {Alpha3: "sit", Alpha2: "", English: []string{"Sino-Tibetan languages"},
		French: []string{"sino-tibétaines, langues"}},
	"sk": {Alpha3: "slo", Alpha2: "sk", English: []string{"Slovak"},
		French: []string{"slovaque"}},
	"sl": {Alpha3: "slv", Alpha2: "sl", English: []string{"Slovenian"},
		French: []string{"slovène"}},
	"sla": {Alpha3: "sla", Alpha2: "", English: []string{"Slavic languages"},
		French: []string{"slaves, langues"}},
	"slo": {Alpha3: "slo", Alpha2: "sk", English: []string{"Slovak"},
		French: []string{"slovaque"}},
	"slv": {Alpha3: "slv", Alpha2: "sl", English: []string{"Slovenian"},
		French: []string{"slovène"}},
	"sm": {Alpha3: "smo", Alpha2: "sm", English: []string{"Samoan"},
		French: []string{"samoan"}},
	"sma": {Alpha3: "sma", Alpha2: "", English: []string{"Southern Sami"},
		French: []string{"sami du Sud"}},
	"sme": {Alpha3: "sme", Alpha2: "se", English: []string{"Northern Sami"},
		French: []string{"sami du Nord"}},
	"smi": {Alpha3: "smi", Alpha2: "", English: []string{"Sami languages"},
		French: []string{"sames, langues"}},
	"smj": {Alpha3: "smj", Alpha2: "", English: []string{"Lule Sami"},
		French: []string{"sami de Lule"}},
	"smn": {Alpha3: "smn", Alpha2: "", English: []string{"Inari Sami"},
		French: []string{"sami d'Inari"}},
	"smo": {Alpha3: "smo", Alpha2: "sm", English: []string{"Samoan"},
		French: []string{"samoan"}},
	"sms": {Alpha3: "sms", Alpha2: "", English: []string{"Skolt Sami"},
		French: []string{"sami skolt"}},
	"sn": {Alpha3: "sna", Alpha2: "sn", English: []string{"Shona"},
		French: []string{"shona"}},
	"sna": {Alpha3: "sna", Alpha2: "sn", English: []string{"Shona"},
		French: []string{"shona"}},
	"snd": {Alpha3: "snd", Alpha2: "sd", English: []string{"Sindhi"},
		French: []string{"sindhi"}},
	"snk": {Alpha3: "snk", Alpha2: "", English: []string{"Soninke"},
		French: []string{"soninké"}},
	"so": {Alpha3: "som", Alpha2: "so", English: []string{"Somali"},
		French: []string{"somali"}},
	"sog": {Alpha3: "sog", Alpha2: "", English: []string{"Sogdian"},
		French: []string{"sogdien"}},
	"som": {Alpha3: "som", Alpha2: "so", English: []string{"Somali"},
		French: []string{"somali"}},
	"son": {Alpha3: "son", Alpha2: "", English: []string{"Songhai languages"},
		French: []string{"songhai, langues"}},
	"sot": {Alpha3: "sot", Alpha2: "st", English: []string{"Sotho, Southern"},
		French: []string{"sotho du Sud"}},
	"spa": {Alpha3: "spa", Alpha2: "es", English: []string{"Spanish", "Castilian"},
		French: []string{"espagnol", "castillan"}},
	"sq": {Alpha3: "alb", Alpha2: "sq", English: []string{"Albanian"},
		French: []string{"albanais"}},
	"sr": {Alpha3: "srp", Alpha2: "sr", English: []string{"Serbian"},
		French: []string{"serbe"}},
	"srd": {Alpha3: "srd", Alpha2: "sc", English: []string{"Sardinian"},
		French: []string{"sarde"}},
	"srn": {Alpha3: "srn", Alpha2: "", English: []string{"Sranan Tongo"},
		French: []string{"sranan tongo"}},
	"srp": {Alpha3: "srp", Alpha2: "sr", English: []string{"Serbian"},
		French: []string{"serbe"}},
	"srr": {Alpha3: "srr", Alpha2: "", English: []string{"Serer"},
		French: []string{"sérère"}},
	"ss": {Alpha3: "ssw", Alpha2: "ss", English: []string{"Swati"},
		French: []string{"swati"}},
	"ssa": {Alpha3: "ssa", Alpha2: "", English: []string{"Nilo-Saharan languages"},
		French: []string{"nilo-sahariennes, langues"}},
	"ssw": {Alpha3: "ssw", Alpha2: "ss", English: []string{"Swati"},
		French: []string{"swati"}},
	"st": {Alpha3: "sot", Alpha2: "st", English: []string{"Sotho, Southern"},
		French: []string{"sotho du Sud"}},
	"su": {Alpha3: "sun", Alpha2: "su", English: []string{"Sundanese"},
		French: []string{"soundanais"}},
	"suk": {Alpha3: "suk", Alpha2: "", English: []string{"Sukuma"},
		French: []string{"sukuma"}},
	"sun": {Alpha3: "sun", Alpha2: "su", English: []string{"Sundanese"},
		French: []string{"soundanais"}},
	"sus": {Alpha3: "sus", Alpha2: "", English: []string{"Susu"},
		French: []string{"soussou"}},
	"sux": {Alpha3: "sux", Alpha2: "", English: []string{"Sumerian"},
		French: []string{"sumérien"}},
	"sv": {Alpha3: "swe", Alpha2: "sv", English: []string{"Swedish"},
		French: []string{"suédois"}},
	"sw": {Alpha3: "swa", Alpha2: "sw", English: []string{"Swahili"},
		French: []string{"swahili"}},
	"swa": {Alpha3: "swa", Alpha2: "sw", English: []string{"Swahili"},
		French: []string{"swahili"}},
	"swe": {Alpha3: "swe", Alpha2: "sv", English: []string{"Swedish"},
		French: []string{"suédois"}},
	"syc": {Alpha3: "syc", Alpha2: "", English: []string{"Classical Syriac"},
		French: []string{"syriaque classique"}},
	"syr": {Alpha3: "syr", Alpha2: "", English: []string{"Syriac"},
		French: []string{"syriaque"}},
	"ta": {Alpha3: "tam", Alpha2: "ta", English: []string{"Tamil"},
		French: []string{"tamoul"}},
	"tah": {Alpha3: "tah", Alpha2: "ty", English: []string{"Tahitian"},
		French: []string{"tahitien"}},
	"tai": {Alpha3: "tai", Alpha2: "", English: []string{"Tai languages"},
		French: []string{"tai, langues"}},
	"tam": {Alpha3: "tam", Alpha2: "ta", English: []string{"Tamil"},
		French: []string{"tamoul"}},
	"tat": {Alpha3: "tat", Alpha2: "tt", English: []string{"Tatar"},
		French: []string{"tatar"}},
	"te": {Alpha3: "tel", Alpha2: "te", English: []string{"Telugu"},
		French: []string{"télougou"}},
	"tel": {Alpha3: "tel", Alpha2: "te", English: []string{"Telugu"},
		French: []string{"télougou"}},
	"tem": {Alpha3: "tem", Alpha2: "", English: []string{"Timne"},
		French: []string{"temne"}},
	"ter": {Alpha3: "ter", Alpha2: "", English: []string{"Tereno"},
		French: []string{"tereno"}},
	"tet": {Alpha3: "tet", Alpha2: "", English: []string{"Tetum"},
		French: []string{"tetum"}},
	"tg": {Alpha3: "tgk", Alpha2: "tg", English: []string{"Tajik"},
		French: []string{"tadjik"}},
	"tgk": {Alpha3: "tgk", Alpha2: "tg", English: []string{"Tajik"},
		French: []string{"tadjik"}},
	"tgl": {Alpha3: "tgl", Alpha2: "tl", English: []string{"Tagalog"},
		French: []string{"tagalog"}},
	"th": {Alpha3: "tha", Alpha2: "th", English: []string{"Thai"},
		French: []string{"thaï"}},
	"tha": {Alpha3: "tha", Alpha2: "th", English: []string{"Thai"},
		French: []string{"thaï"}},
	"ti": {Alpha3: "tir", Alpha2: "ti", English: []string{"Tigrinya"},
		French: []string{"tigrigna"}},
	"tib": {Alpha3: "tib", Alpha2: "bo", English: []string{"Tibetan"},
		French: []string{"tibétain"}},
	"tig": {Alpha3: "tig", Alpha2: "", English: []string{"Tigre"},
		French: []string{"tigré"}},
	"tir": {Alpha3: "tir", Alpha2: "ti", English: []string{"Tigrinya"},
		French: []string{"tigrigna"}},
	"tiv": {Alpha3: "tiv", Alpha2: "", English: []string{"Tiv"},
		French: []string{"tiv"}},
	"tk": {Alpha3: "tuk", Alpha2: "tk", English: []string{"Turkmen"},
		French: []string{"turkmène"}},
	"tkl": {Alpha3: "tkl", Alpha2: "", English: []string{"Tokelau"},
		French: []string{"tokelau"}},
	"tl": {Alpha3: "tgl", Alpha2: "tl", English: []string{"Tagalog"},
		French: []string{"tagalog"}},
	"tlh": {Alpha3: "tlh", Alpha2: "", English: []string{"Klingon", "tlhIngan-Hol"},
		French: []string{"klingon"}},
	"tli": {Alpha3: "tli", Alpha2: "", English: []string{"Tlingit"},
		French: []string{"tlingit"}},
	"tmh": {Alpha3: "tmh", Alpha2: "", English: []string{"Tamashek"},
		French: []string{"tamacheq"}},
	"tn": {Alpha3: "tsn", Alpha2: "tn", English: []string{"Tswana"},
		French: []string{"tswana"}},
	"to": {Alpha3: "ton", Alpha2: "to", English: []string{"Tonga (Tonga Islands)"},
		French: []string{"tongan (Îles Tonga)"}},
	"tog": {Alpha3: "tog", Alpha2: "", English: []string{"Tonga (Nyasa)"},
		French: []string{"tonga (Nyasa)"}},
	"ton": {Alpha3: "ton", Alpha2: "to", English: []string{"Tonga (Tonga Islands)"},
		French: []string{"tongan (Îles Tonga)"}},
	"tpi": {Alpha3: "tpi", Alpha2: "", English: []string{"Tok Pisin"},
		French: []string{"tok pisin"}},
	"tr": {Alpha3: "tur", Alpha2: "tr", English: []string{"Turkish"},
		French: []string{"turc"}},
	"ts": {Alpha3: "tso", Alpha2: "ts", English: []string{"Tsonga"},
		French: []string{"tsonga"}},
	"tsi": {Alpha3: "tsi", Alpha2: "", English: []string{"Tsimshian"},
		French: []string{"tsimshian"}},
	"tsn": {Alpha3: "tsn", Alpha2: "tn", English: []string{"Tswana"},
		French: []string{"tswana"}},
	"tso": {Alpha3: "tso", Alpha2: "ts", English: []string{"Tsonga"},
		French: []string{"tsonga"}},
	"tt": {Alpha3: "tat", Alpha2: "tt", English: []string{"Tatar"},
		French: []string{"tatar"}},
	"tuk": {Alpha3: "tuk", Alpha2: "tk", English: []string{"Turkmen"},
		French: []string{"turkmène"}},
	"tum": {Alpha3: "tum", Alpha2: "", English: []string{"Tumbuka"},
		French: []string{"tumbuka"}},
	"tup": {Alpha3: "tup", Alpha2: "", English: []string{"Tupi languages"},
		French: []string{"tupi, langues"}},
	"tur": {Alpha3: "tur", Alpha2: "tr", English: []string{"Turkish"},
		French: []string{"turc"}},
	"tut": {Alpha3: "tut", Alpha2: "", English: []string{"Altaic languages"},
		French: []string{"altaïques, langues"}},
	"tvl": {Alpha3: "tvl", Alpha2: "", English: []string{"Tuvalu"},
		French: []string{"tuvalu"}},
	"tw": {Alpha3: "twi", Alpha2: "tw", English: []string{"Twi"},
		French: []string{"twi"}},
	"twi": {Alpha3: "twi", Alpha2: "tw", English: []string{"Twi"},
		French: []string{"twi"}},
	"ty": {Alpha3: "tah", Alpha2: "ty", English: []string{"Tahitian"},
		French: []string{"tahitien"}},
	"tyv": {Alpha3: "tyv", Alpha2: "", English: []string{"Tuvinian"},
		French: []string{"touva"}},
	"udm": {Alpha3: "udm", Alpha2: "", English: []string{"Udmurt"},
		French: []string{"oudmourte"}},
	"ug": {Alpha3: "uig", Alpha2: "ug", English: []string{"Uighur", "Uyghur"},
		French: []string{"ouïgour"}},
	"uga": {Alpha3: "uga", Alpha2: "", English: []string{"Ugaritic"},
		French: []string{"ougaritique"}},
	"uig": {Alpha3: "uig", Alpha2: "ug", English: []string{"Uighur", "Uyghur"},
		French: []string{"ouïgour"}},
	"uk": {Alpha3: "ukr", Alpha2: "uk", English: []string{"Ukrainian"},
		French: []string{"ukrainien"}},
	"ukr": {Alpha3: "ukr", Alpha2: "uk", English: []string{"Ukrainian"},
		French: []string{"ukrainien"}},
	"umb": {Alpha3: "umb", Alpha2: "", English: []string{"Umbundu"},
		French: []string{"umbundu"}},
	"und": {Alpha3: "und", Alpha2: "", English: []string{"Undetermined"},
		French: []string{"indéterminée"}},
	"ur": {Alpha3: "urd", Alpha2: "ur", English: []string{"Urdu"},
		French: []string{"ourdou"}},
	"urd": {Alpha3: "urd", Alpha2: "ur", English: []string{"Urdu"},
		French: []string{"ourdou"}},
	"uz": {Alpha3: "uzb", Alpha2: "uz", English: []string{"Uzbek"},
		French: []string{"ouszbek"}},
	"uzb": {Alpha3: "uzb", Alpha2: "uz", English: []string{"Uzbek"},
		French: []string{"ouszbek"}},
	"vai": {Alpha3: "vai", Alpha2: "", English: []string{"Vai"},
		French: []string{"vaï"}},
	"ve": {Alpha3: "ven", Alpha2: "ve", English: []string{"Venda"},
		French: []string{"venda"}},
	"ven": {Alpha3: "ven", Alpha2: "ve", English: []string{"Venda"},
		French: []string{"venda"}},
	"vi": {Alpha3: "vie", Alpha2: "vi", English: []string{"Vietnamese"},
		French: []string{"vietnamien"}},
	"vie": {Alpha3: "vie", Alpha2: "vi", English: []string{"Vietnamese"},
		French: []string{"vietnamien"}},
	"vo": {Alpha3: "vol", Alpha2: "vo", English: []string{"Volapük"},
		French: []string{"volapük"}},
	"vol": {Alpha3: "vol", Alpha2: "vo", English: []string{"Volapük"},
		French: []string{"volapük"}},
	"vot": {Alpha3: "vot", Alpha2: "", English: []string{"Votic"},
		French: []string{"vote"}},
	"wa": {Alpha3: "wln", Alpha2: "wa", English: []string{"Walloon"},
		French: []string{"wallon"}},
	"wak": {Alpha3: "wak", Alpha2: "", English: []string{"Wakashan languages"},
		French: []string{"wakashanes, langues"}},
	"wal": {Alpha3: "wal", Alpha2: "", English: []string{"Wolaitta", "Wolaytta"},
		French: []string{"wolaitta", "wolaytta"}},
	"war": {Alpha3: "war", Alpha2: "", English: []string{"Waray"},
		French: []string{"waray"}},
	"was": {Alpha3: "was", Alpha2: "", English: []string{"Washo"},
		French: []string{"washo"}},
	"wel": {Alpha3: "wel", Alpha2: "cy", English: []string{"Welsh"},
		French: []string{"gallois"}},
	"wen": {Alpha3: "wen", Alpha2: "", English: []string{"Sorbian languages"},
		French: []string{"sorabes, langues"}},
	"wln": {Alpha3: "wln", Alpha2: "wa", English: []string{"Walloon"},
		French: []string{"wallon"}},
	"wo": {Alpha3: "wol", Alpha2: "wo", English: []string{"Wolof"},
		French: []string{"wolof"}},
	"wol": {Alpha3: "wol", Alpha2: "wo", English: []string{"Wolof"},
		French: []string{"wolof"}},
	"xal": {Alpha3: "xal", Alpha2: "", English: []string{"Kalmyk", "Oirat"},
		French: []string{"kalmouk", "oïrat"}},
	"xh": {Alpha3: "xho", Alpha2: "xh", English: []string{"Xhosa"},
		French: []string{"xhosa"}},
	"xho": {Alpha3: "xho", Alpha2: "xh", English: []string{"Xhosa"},
		French: []string{"xhosa"}},
	"yao": {Alpha3: "yao", Alpha2: "", English: []string{"Yao"},
		French: []string{"yao"}},
	"yap": {Alpha3: "yap", Alpha2: "", English: []string{"Yapese"},
		French: []string{"yapois"}},
	"yi": {Alpha3: "yid", Alpha2: "yi", English: []string{"Yiddish"},
		French: []string{"yiddish"}},
	"yid": {Alpha3: "yid", Alpha2: "yi", English: []string{"Yiddish"},
		French: []string{"yiddish"}},
	"yo": {Alpha3: "yor", Alpha2: "yo", English: []string{"Yoruba"},
		French: []string{"yoruba"}},
	"yor": {Alpha3: "yor", Alpha2: "yo", English: []string{"Yoruba"},
		French: []string{"yoruba"}},
	"ypk": {Alpha3: "ypk", Alpha2: "", English: []string{"Yupik languages"},
		French: []string{"yupik, langues"}},
	"za": {Alpha3: "zha", Alpha2: "za", English: []string{"Zhuang", "Chuang"},
		French: []string{"zhuang", "chuang"}},
	"zap": {Alpha3: "zap", Alpha2: "", English: []string{"Zapotec"},
		French: []string{"zapotèque"}},
	"zbl": {Alpha3: "zbl", Alpha2: "", English: []string{"Blissymbols", "Blissymbolics", "Bliss"},
		French: []string{"symboles Bliss", "Bliss"}},
	"zen": {Alpha3: "zen", Alpha2: "", English: []string{"Zenaga"},
		French: []string{"zenaga"}},
	"zgh": {Alpha3: "zgh", Alpha2: "", English: []string{"Standard Moroccan Tamazight"},
		French: []string{"amazighe standard marocain"}},
	"zh": {Alpha3: "chi", Alpha2: "zh", English: []string{"Chinese"},
		French: []string{"chinois"}},
	"zha": {Alpha3: "zha", Alpha2: "za", English: []string{"Zhuang", "Chuang"},
		French: []string{"zhuang", "chuang"}},
	"znd": {Alpha3: "znd", Alpha2: "", English: []string{"Zande languages"},
		French: []string{"zandé, langues"}},
	"zu": {Alpha3: "zul", Alpha2: "zu", English: []string{"Zulu"},
		French: []string{"zoulou"}},
	"zul": {Alpha3: "zul", Alpha2: "zu", English: []string{"Zulu"},
		French: []string{"zoulou"}},
	"zun": {Alpha3: "zun", Alpha2: "", English: []string{"Zuni"},
		French: []string{"zuni"}},
	"zxx": {Alpha3: "zxx", Alpha2: "", English: []string{"No linguistic content", "Not applicable"},
		French: []string{"pas de contenu linguistique", "non applicable"}},
	"zza": {Alpha3: "zza", Alpha2: "", English: []string{"Zaza", "Dimili", "Dimli", "Kirdki", "Kirmanjki", "Zazaki"},
		French: []string{"zaza", "dimili", "dimli", "kirdki", "kirmanjki", "zazaki"}}}
